# Generated by Django 5.2.8 on 2026-01-16 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('entreprise', models.CharField(blank=True, max_length=100, verbose_name='Entreprise')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photo de profil')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('newsletter', models.BooleanField(default=True, verbose_name='Abonné newsletter')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
